### ISSUE TITLE
Change /shut_the_fuck_up behaviour and add /zzz command

### ISSUE THREAD

**Issue by mishuill** [andrewyazura/discord-music-bot#2]
- Make /shut_the_fuck_up stop playback of a current track, without bot leaving the voice channel.
- Change /shut_the_fuck_up to /shut-the-fuck-up or /stfu for easier typing. 
- Make /zzz command to make bot leave the voice channel.

**Comment by andrewyazura** [comment]
Valid points, but I'd like to make some changes:
1. /shut_the_fuck_up will still make bot disconnect completely. If you want to pause, use /pause
2. I'll rename /pause to /shut_up (or add an alias)
3. No /zzz

**Comment by andrewyazura** [comment]
Basically, resolved in 9819f09e734f22f56f52edf72c0476c8f2afc0c5
